[package]
name = "lu_packets_derive"
version = "0.2.0"
authors = ["lcdr"]
edition = "2024"
license = "AGPL-3.0-or-later"
repository = "https://github.com/jadebenn/lu_packets/"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[lints.clippy]
pedantic = "warn"
